### ISSUE TITLE
Adding "Product Unit" neurons (or layers)

### ISSUE THREAD

**Issue by mtewes** [mtewes/tenbilac#14]
There is quite a bit of litterature on multiplicative networks, and it sounds very good so far, nice!
One paper I like a lot is:
http://sci2s.ugr.es/keel/pdf/specific/articulo/Schmidtt%20on-the-complexity-of.pdf

Will work on this in a dedicated branch #14

**Comment by mtewes** [comment]
According to Leerink et al. (1995) page 2, the initialization is important and should not be done with small values around 0.0, and local minima get worse. Let's see.

**Comment by mtewes** [comment]
Python + numpy implementations of the product unit layer are done, but they are probably much slower than the equivalent "sum" layers. We might soon need SWIG here. Now writing a simple test that "learns" the multiplication of 2 numbers...

**Comment by mtewes** [comment]
Nets can now include product layers, training remains unchanged so far. [-3,3] means the first hidden layer is composed of 3 product units. Now working on that test...

**Comment by mtewes** [comment]
Learning z = x * y with 1000 examples.
The prediction error is shown as color.

- with 2 layers of 5 conventional neurons (51 parameters), 30 seconds of training:
![screen shot 2016-11-25 at 16 00 18](https://cloud.githubusercontent.com/assets/1928653/20628810/7f9e01e0-b328-11e6-9baa-470911d9bce6.png)

- and with a **single hidden product neuron**, randomly intialized, 0.5 seconds of training:
![screen shot 2016-11-25 at 16 06 30](https://cloud.githubusercontent.com/assets/1928653/20628925/30e742c2-b329-11e6-81f5-8f426e6a2a04.png)

Note the smaller color scale of the latter.
Seems to work, and we can also confirm that sum-units are badly suited for multiplications.

The "report" is also automatically adapted, after training it looks like
```
[2|1/*iden|1/iden=5]
Layer 'h0', mode mult, ni 2, nn 1, actfct iden:
    output 0 = iden ( prod (input ** [ 0.99999963  0.99999962]) + 0.134301267119 )
Layer 'o', mode sum, ni 1, nn 1, actfct iden:
    output 0 = iden ( input * [ 0.99999999] + -0.134301381374 )
```

**Comment by kuntzer** [comment]
That does look nice!

**Comment by mtewes** [comment]
I pushed the demo code, 
demo/test_mult_learn.py

One big issue to think about is the "normalization", the issues with negative values fed into "product units", and the choice of activation functions that get "fed" into later product-unit layers. It's a whole new world to explore, but I would love to not explore it for too long :)
I guess it would be good to keep the "signs" of ellipticity components somehow, i.e. use a "-11" norm, and find a hack so that it works with the product units. Using a "01" normer in front of a product unit would be a shame. We precisely want those units to be able to rescale numbers which might be positive or negative by multiplying their amplitude. Maybe some power-raising that artificially keeps the sign could work (and reinventing maths is fun).

**Comment by mtewes** [comment]
Routes I'm trying:

- Algebraic requirement: dealing with negative inputs. From {Durbin:1989kc} :

> We want to be able to consider negative inputs because the non-linear characteristics of product units, which we want to use computationally, are centered on the origin.

Explored custom solution, a bit of a hack: make the product units always return a value with the same sign as their first input. Using np.sign. All the exponentiation and product stuff works on np.fabs(inputs). This makes their behavior "odd" around 0.0 of the first input.


- Later: add a "sa1"-type to Normer (for "scale abs to 1"). What it does is to scale the data using only a positive multiplicative factor, so that the absolute value of the output is always smaller or equal to 1: `x /= max(abs(x))`. This puts "g1" between -1 and 1, while avoiding to put the "mean rad" or "mean flux" close 0.0. In other words it preserves the sign. Aim is to avoid the need for a "sum"-layer (with bias offsets) in front of the "product"-layer.

**Comment by mtewes** [comment]
Todo in order to test the point 2. above:
- implement the "sa1"-normer
- implement some clever initial settings for product unit layers (maybe this is bonus, will first try without).

**Comment by mtewes** [comment]
About the initial "identity" settings, there is another interesting aspect: so far, for a network with a single output, each layer was only set to "transport" the first input. All other neurons started from zero. It could be much more interesting for each i-th neuron of each layer to transport the i-th input. Given that we train layers starting by the end, the last layer would directly see "all inputs". Of course, if you have more hidden nodes than inputs, you'll still have some "joker" neurons starting from zero.
Will implement this in a configurable way, to leave the choice to "transport" only the first n inputs or to transport all inputs as far as possible into the network.

**Comment by mtewes** [comment]
About initial noise in the "weights" (== exponents) of mult-layers:
- [x] **new option ininoisemultwscale**, default = 0.1 (only affects nets with mult layers, of course).
- [ ] experiment with not adding noise here, or adding fixed exponents, say 0.1.

**Comment by mtewes** [comment]
I'll experiment with restricting the multiplication-layer to positive powers, i.e., avoid divisions.

**Comment by mtewes** [comment]
Closing this, it works. Next upgrades will be done in a new issue and branch.
