### ISSUE TITLE
Visualisation tools for Tenbilac

### ISSUE THREAD

**Issue by kuntzer** [mtewes/tenbilac#16]
I wrote a script that produces [Tensorflow Playground-like](http://playground.tensorflow.org) plots for Tenbilac. I will add to `tenbilac.plot.py` this in a new branch (#16).

![network_viz](https://cloud.githubusercontent.com/assets/7694359/20745492/e98882e4-b6e1-11e6-8be9-58d9bba55146.png)

**Comment by mtewes** [comment]
Nice!

**Comment by kuntzer** [comment]
Done. This is now part of the autoplots with, if availble, the correct labelling of the inputs and outputs. Will merge soon.

**Comment by kuntzer** [comment]
Done!

**Comment by mtewes** [comment]
Just thinking (not urgent -- once all the rest is working nicely): could be interesting to
- revert y, so that first feature is first
- write the iteration number on the plot (title), why not add the training time as done in sumevo etc.
... to make an animation for talks of the training.

**Comment by mtewes** [comment]
Further points:
- I think it should take a Net (and not a Training) object. It's role is very close to net.report(). If training-related stuff is desired to be visible on the plot, this can be passed to the title or other kwargs...

**Comment by mtewes** [comment]
- somehow make the biases more prominent (maybe as circles with varyign thickness around the nodes) ?
- add act function ?

A netviz animation (this one does not yet start at iteration 0, and simultaneously optimizes the Mult and the Sum layer:
https://uni-bonn.sciebo.de/index.php/s/DqbiMgTByiEkFcy

**Comment by kuntzer** [comment]
A summary of the above points and a few others:
- [ ] Debug the display for the name of the cost function
- [ ] Use "+" and "x" symbols to mark mult and sum neurons ? (only if not only +)
- [ ] somehow make the biases more prominent (maybe as circles with varyign thickness around the nodes) ?
- [ ] Add act fct name somewhere

**Comment by mtewes** [comment]
Nice -- I really like this plot, I guess we'll also use it in papers!

I would say that
- optimization algo 
- cost function name and value, structure of training data (cases, reas, minibatches etc)
- iteration, 
- training time
... could be passed as free text in an optional text display, and should maybe not be hard-coded in the plot itself (to keep the later simple and flexible).

With this option, I guess that multnets don't even need special handling. They are just normal nets which happen to have a mult layer specially initialized.

**Comment by kuntzer** [comment]
working on this in branch 'viznet'

**Comment by kuntzer** [comment]
> Should be taking a net rather than a Training

mmmh, that would be a big change: a net does not know the error function or the in-/outputs names. The plot would be less interesting. I could imagine a very adaptive plot that could take a `train` or a `net`, but the polymorphism in Python is a bit messy.

The plot looks like this now:
_if the net contains only summation layers:_
![network_viz](https://cloud.githubusercontent.com/assets/7694359/21183827/f833575a-c209-11e6-85ff-9743d9d9ac72.png)
_if the net contains both modes:_
![network_viz](https://cloud.githubusercontent.com/assets/7694359/21183839/09f1f6a4-c20a-11e6-9504-07cc6db7426c.png)
The title is an argument that is by default `"default"`. This will generate the string shown in the plots, but any other string can be passed to `title`.

Other suggestions?

**Comment by mtewes** [comment]
But this plot is really about a net, and not about a training! A yes, a net knows and nicely handles its inames and onames!
Information about the cost function, iteration number, should be passed into a "title" or "textlines" argument. Note that the first part of the current title is in fact what is shown in the plot.

**Comment by kuntzer** [comment]
Okay, done. The changes were easy enough

**Comment by kuntzer** [comment]
Let's close this. (at least for now)
