### ISSUE TITLE
Plot with evolution of MSB terms during training

### ISSUE THREAD

**Issue by mtewes** [mtewes/tenbilac#18]

**Comment by kuntzer** [comment]
Nice. The fact that the colours become lighter with iteration means that the differences between the samples increase?

**Comment by mtewes** [comment]
No, alpha and lightness do not change here. It's just that subtle differences between cases become visible only after a bit of training.

**Comment by kuntzer** [comment]
okay!

**Comment by mtewes** [comment]
In a more realistic case:
![screen shot 2016-12-07 at 17 07 58](https://cloud.githubusercontent.com/assets/1928653/20975559/26f76b9a-bca0-11e6-9111-5bffae007092.png)

Issues with this
- many iterations -> takes long time to plot. Don't save every iteration ?
- after a restart of the training, training data is shuffled, and colors (features) that the plot uses don't match to the biases that where saved before. So only the last block of colors is good.

It's interesting to see and understand this plot, but maybe this is not a top priority.

**Comment by mtewes** [comment]
Done with the plot -- it is activated by a kwarg to the training constructor.
Will now find a solution to pass it as option from MegaLUT.

**Comment by mtewes** [comment]
Note that the problem (above) with the many iterations is now fixed. We only save some snapshots.

**Comment by kuntzer** [comment]
:+1:

**Comment by mtewes** [comment]
Done and merged.
