### ISSUE TITLE
Add a custom easy-to-understand "first approach" optimization

### ISSUE THREAD

**Issue by mtewes** [mtewes/tenbilac#20]
I have in mind something brute force, that respects the idea that our networks are small, start with something already reasonable, and that "sparse" changes can have a huge effect.
Example: loop through all params, try out -1, -0.5, +0.5, +1, and then perform a single step changing just this parameter.

**Comment by mtewes** [comment]
I started working on this, but will take care of #18 at the same time. The purpose of all this is to see why the current bfgs gets stuck in "obviously bad" solutions.

**Comment by kuntzer** [comment]
In the spirit of a first approach, I tried a very very simple networks to predict tru_s1:

(tru_s1, adamom_g1, adamom_g2, tru_rad) -> 4 neuron/tanh -> 1 neuron/iden:

![netviz_optit00195](https://cloud.githubusercontent.com/assets/7694359/20800412/b45832cc-b7e5-11e6-93bb-afd089f770f2.png)

which took an amazingly long time to train (8min)
The remaining bias is still quite large O(10⁻⁴)

![bias](https://cloud.githubusercontent.com/assets/7694359/20800424/c0e7392a-b7e5-11e6-8aef-2664ecf68961.png)

**Comment by mtewes** [comment]
Now restructuring the training, to support the choice of algorithm (or several, in fact) at a high level (megalut wrapper).

**Comment by mtewes** [comment]
@kuntzer I've made PRs for both tenbilac and megalut. They go together (you need both), but I guess that's ok given our current stage of experimentation.

**Comment by kuntzer** [comment]
Okay, I'm looking at it now

**Comment by mtewes** [comment]
Merged. It's still a mess to pass arguments through the megalut tenbilacwrapper, but at least this makes it cleaner to write e.g. your own hard-code optimizer (for a specific task) and using it.
