### ISSUE TITLE
During training, a copy of the config file should be saved in the workdir

### ISSUE THREAD

**Issue by mtewes** [mtewes/tenbilac#36]
Best is probably to really just shutil copy it there.

**Comment by mtewes** [comment]
Will address this, as well as other minor points in a branch "post-xmas-fixes", opening now.

- [ ] copy config file with a timestamp
- [ ] make predictions multicpu

**Comment by mtewes** [comment]
I've fixed a random seed issue in training (pushed to current PR): all processes where using exactly the same minibatches (and maybe even worse, not sure if there is some "random" involved in bfgs).

**Comment by kuntzer** [comment]
Okay, I'll update it!

**Comment by mtewes** [comment]
- [ ] Make a method to "minimize" a workdir, keeping only the (small) information needed for predictions, and getting rid of all the plots and lists and logs.

**Comment by mtewes** [comment]
This "minimized" version could be written inside of the current workdir automatically after each training. Maybe even with a timestamp, so that previous training results can be easily reused.

**Comment by mtewes** [comment]
All done, except for the multi-cpu predictions (not that urgent), closing.
