### ISSUE TITLE
By default, an existing Normer should be reused instead of making a new one

### ISSUE THREAD

**Issue by mtewes** [mtewes/tenbilac#42]
... when restarting an existing training.
Add a setting in the config file to control this.

**Comment by mtewes** [comment]
I'll keep working in the post-xmas-fixes branch for this.
Any comments welcome!
I'm also wondering if the committe-member directories should not be better just have always the same names, say "member001", instead of using the config name. OK if I change this (breaks backwards compatibility with existing trainings), @kuntzer ?

**Comment by kuntzer** [comment]
Seems a good idea! I can change the names manually anyhow

**Comment by mtewes** [comment]
This is implemented, but I'm busy with the "minimize". It turns out that we also kept carrying around the "cache" of each layer, dealing with this right now. Will push asap.

**Comment by kuntzer** [comment]
Oh, you mean we could be freeing a lot of memory?

**Comment by mtewes** [comment]
Not while running (except if we don't use the cache, which maybe should also be a configurable option). But when saving to disk, yes.

**Comment by mtewes** [comment]
All implemented and merged, closing.
